/**
 * Pointer-based drag sessions (mousedown + mousemove), used instead of HTML5
 * drag-and-drop: the native DnD path in WebKitGTK can freeze the webview
 * compositor (black screen), and pointer tracking gives Hyprland-style live
 * feedback while dragging.
 */

export interface PointerDragOptions {
  /** Pixels of pointer travel before the drag actually starts (default 4) */
  threshold?: number;
  /** Cursor shown while dragging (default 'grabbing') */
  cursor?: string;
  /** Builds the element that follows the pointer; positioned near the cursor */
  createGhost?: () => HTMLElement;
  /** Called once, when the threshold is exceeded */
  onDragStart?: () => void;
  /** Called on every pointer move after the drag has started */
  onDragMove?: (x: number, y: number) => void;
  /** Called on release, only if the drag actually started */
  onDrop?: (x: number, y: number) => void;
  /** Always called on release, after onDrop */
  onEnd?: () => void;
}

export interface DropRect {
  left: number;
  top: number;
  width: number;
  height: number;
}

/** Returns true if the point lies inside the rect */
export function rectContains(rect: DropRect, x: number, y: number): boolean {
  return (
    x >= rect.left &&
    x <= rect.left + rect.width &&
    y >= rect.top &&
    y <= rect.top + rect.height
  );
}

const GHOST_OFFSET = 14;

/**
 * Starts a drag session from a mousedown position. Below the threshold the
 * session is inert, so regular clicks on the source element keep working.
 * Once dragging, a full-screen overlay owns the pointer and an optional ghost
 * element follows the cursor; if the drag started, the click that follows the
 * release is swallowed.
 */
export function startPointerDrag(startX: number, startY: number, options: PointerDragOptions): void {
  const {
    threshold = 4,
    cursor = 'grabbing',
    createGhost,
    onDragStart,
    onDragMove,
    onDrop,
    onEnd,
  } = options;

  let started = false;
  let overlay: HTMLDivElement | null = null;
  let ghost: HTMLElement | null = null;

  const positionGhost = (x: number, y: number) => {
    if (!ghost) return;
    ghost.style.transform = `translate(${x + GHOST_OFFSET}px, ${y + GHOST_OFFSET}px)`;
  };

  const begin = (x: number, y: number) => {
    started = true;
    document.body.style.cursor = cursor;
    // Overlay prevents editors/iframes from capturing pointer events mid-drag
    overlay = document.createElement('div');
    overlay.style.cssText = `position:fixed;inset:0;z-index:9999;cursor:${cursor};user-select:none`;
    document.body.appendChild(overlay);
    if (createGhost) {
      ghost = createGhost();
      ghost.style.position = 'fixed';
      ghost.style.left = '0';
      ghost.style.top = '0';
      ghost.style.pointerEvents = 'none';
      ghost.style.zIndex = '10000';
      overlay.appendChild(ghost);
      positionGhost(x, y);
    }
    onDragStart?.();
  };

  const handleMouseMove = (e: MouseEvent) => {
    if (!started) {
      if (Math.abs(e.clientX - startX) < threshold && Math.abs(e.clientY - startY) < threshold) {
        return;
      }
      begin(e.clientX, e.clientY);
    }
    positionGhost(e.clientX, e.clientY);
    onDragMove?.(e.clientX, e.clientY);
  };

  const handleMouseUp = (e: MouseEvent) => {
    document.removeEventListener('mousemove', handleMouseMove);
    document.removeEventListener('mouseup', handleMouseUp);
    if (started) {
      document.body.style.cursor = 'default';
      overlay?.remove();
      // Swallow the click generated by this release. The guard removes itself
      // after one click; the timeout clears it when no click follows at all
      const suppressClick = (clickEvent: MouseEvent) => {
        clickEvent.stopPropagation();
        clickEvent.preventDefault();
        window.removeEventListener('click', suppressClick, true);
      };
      window.addEventListener('click', suppressClick, true);
      setTimeout(() => window.removeEventListener('click', suppressClick, true), 0);
      onDrop?.(e.clientX, e.clientY);
    }
    onEnd?.();
  };

  document.addEventListener('mousemove', handleMouseMove);
  document.addEventListener('mouseup', handleMouseUp);
}
