import { describe, it, expect, vi, afterEach } from 'vitest';
import { rectContains, startPointerDrag } from '../../src/utils/pointerDrag';

const move = (x: number, y: number) =>
  document.dispatchEvent(new MouseEvent('mousemove', { clientX: x, clientY: y }));

const release = (x: number, y: number) =>
  document.dispatchEvent(new MouseEvent('mouseup', { clientX: x, clientY: y }));

afterEach(() => {
  // Drain any pending click suppressor
  vi.useRealTimers();
  document.body.innerHTML = '';
  document.body.style.cursor = 'default';
});

describe('rectContains', () => {
  const rect = { left: 10, top: 20, width: 100, height: 50 };

  it('returns true for points inside the rect', () => {
    expect(rectContains(rect, 50, 40)).toBe(true);
  });

  it('includes the edges', () => {
    expect(rectContains(rect, 10, 20)).toBe(true);
    expect(rectContains(rect, 110, 70)).toBe(true);
  });

  it('returns false for points outside the rect', () => {
    expect(rectContains(rect, 9, 40)).toBe(false);
    expect(rectContains(rect, 50, 71)).toBe(false);
  });
});

describe('startPointerDrag', () => {
  it('does not start the drag below the threshold', () => {
    const onDragStart = vi.fn();
    const onDrop = vi.fn();
    const onEnd = vi.fn();
    startPointerDrag(100, 100, { threshold: 5, onDragStart, onDrop, onEnd });

    move(102, 101);
    release(102, 101);

    expect(onDragStart).not.toHaveBeenCalled();
    expect(onDrop).not.toHaveBeenCalled();
    expect(onEnd).toHaveBeenCalledTimes(1);
  });

  it('starts once the threshold is exceeded and reports moves and the drop', () => {
    const onDragStart = vi.fn();
    const onDragMove = vi.fn();
    const onDrop = vi.fn();
    startPointerDrag(100, 100, { threshold: 5, onDragStart, onDragMove, onDrop });

    move(120, 100);
    move(150, 130);
    release(150, 130);

    expect(onDragStart).toHaveBeenCalledTimes(1);
    expect(onDragMove).toHaveBeenLastCalledWith(150, 130);
    expect(onDrop).toHaveBeenCalledWith(150, 130);
  });

  it('mounts an overlay and ghost while dragging and removes them on release', () => {
    const ghost = document.createElement('div');
    ghost.textContent = 'ghost';
    startPointerDrag(0, 0, { threshold: 1, createGhost: () => ghost });

    move(50, 50);
    expect(document.body.contains(ghost)).toBe(true);

    release(50, 50);
    expect(document.body.contains(ghost)).toBe(false);
  });

  it('detaches its listeners after release', () => {
    const onDragMove = vi.fn();
    startPointerDrag(0, 0, { threshold: 1, onDragMove });

    move(50, 50);
    release(50, 50);
    onDragMove.mockClear();

    move(80, 80);
    expect(onDragMove).not.toHaveBeenCalled();
  });

  it('swallows only the click generated by the drag release', () => {
    vi.useFakeTimers();
    const clickSpy = vi.fn();
    document.addEventListener('click', clickSpy);
    startPointerDrag(0, 0, { threshold: 1 });

    move(50, 50);
    release(50, 50);
    document.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    expect(clickSpy).not.toHaveBeenCalled();

    vi.runAllTimers();
    document.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    expect(clickSpy).toHaveBeenCalledTimes(1);
    document.removeEventListener('click', clickSpy);
  });
});
